---
services: # https://github.com/pi-hole/docker-pi-hole/
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: 'Europe/Berlin'
      PIHOLE_DNS_: '8.8.8.8;1.1.1.1'
      DNSSEC: 'false'
      VIRTUAL_HOST: 'pihole'
      WEBTHEME: 'default-dark'
      DNSMASQ_LISTENING: 'all'
      SKIPGRAVITYONBOOT: 'true'
    volumes:
      - '/home/loogle/docker-data-volumes/pihole/etc..pihole:/etc/pihole'
      - '/home/loogle/docker-data-volumes/pihole/etc..dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    network_mode: service:pihole-tailscale

  pihole-tailscale: # https://tailscale.com/kb/1282/docker
    image: tailscale/tailscale:latest
    container_name: pihole-tailscale
    hostname: pihole
    environment:
      - TS_AUTHKEY=tskey-auth-kT7qMM8bzb11CNTRL-cseyb29mmxaz5j1MVxh3yaHgLrB7TT5R
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_HOSTNAME=pihole
      - TS_ROUTES=192.168.1.0/24 #need to go into tailscale and toggle the subnet to approved once contianer is up
    volumes:
      - /home/loogle/docker-data-volumes/pihole/tailscale/var..lib..tailscale:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped